// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApLWUSLIAry-WF13U-rFFf2Syd66jHsBk',
    appId: '1:802830422602:web:2802cada761ee9c88f8cb3',
    messagingSenderId: '802830422602',
    projectId: 'hw2-new-f402b',
    authDomain: 'hw2-new-f402b.firebaseapp.com',
    storageBucket: 'hw2-new-f402b.firebasestorage.app',
    measurementId: 'G-8RRPYMTDXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwApvfBjfWPMtY86uxIFqQRpk31AUIXkw',
    appId: '1:802830422602:android:1b9a8381bf84a5078f8cb3',
    messagingSenderId: '802830422602',
    projectId: 'hw2-new-f402b',
    storageBucket: 'hw2-new-f402b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi-_xlVDvwEhBaYyxubtSEx5YKJ9T8G7k',
    appId: '1:802830422602:ios:61dc9126b3770a428f8cb3',
    messagingSenderId: '802830422602',
    projectId: 'hw2-new-f402b',
    storageBucket: 'hw2-new-f402b.firebasestorage.app',
    iosBundleId: 'com.example.hw2New',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi-_xlVDvwEhBaYyxubtSEx5YKJ9T8G7k',
    appId: '1:802830422602:ios:61dc9126b3770a428f8cb3',
    messagingSenderId: '802830422602',
    projectId: 'hw2-new-f402b',
    storageBucket: 'hw2-new-f402b.firebasestorage.app',
    iosBundleId: 'com.example.hw2New',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApLWUSLIAry-WF13U-rFFf2Syd66jHsBk',
    appId: '1:802830422602:web:a4d8ff19c2b317f08f8cb3',
    messagingSenderId: '802830422602',
    projectId: 'hw2-new-f402b',
    authDomain: 'hw2-new-f402b.firebaseapp.com',
    storageBucket: 'hw2-new-f402b.firebasestorage.app',
    measurementId: 'G-6NSQB308FV',
  );
}
